export const GET_ALL_TODO_REQUEST = "GET_ALL_TODO_REQUEST"
export const GET_ALL_TODO_REQUEST_SUCCESS = "GET_ALL_TODO_REQUEST_SUCCESS"
export const GET_ALL_TODO_REQUEST_FAIL = "GET_ALL_TODO_REQUEST_FAIL"


export const GET_SINGLE_TODO_REQUEST = "GET_SINGLE_TODO_REQUEST"
export const GET_SINGLE_TODO_REQUEST_SUCCESS = "GET_SINGLE_TODO_REQUEST_SUCCESS"
export const GET_SINGLE_TODO_REQUEST_FAIL = "GET_SINGLE_TODO_REQUEST_FAIL"

export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST"
export const ADD_TODO_REQUEST_SUCCESS = "ADD_TODO_REQUEST_SUCCESS"
export const ADD_TODO_REQUEST_FAIL = "ADD_TODO_REQUEST_FAIL"

export const UPDATE_TODO_REQUEST = "UPDATE_TODO_REQUEST"
export const UPDATE_TODO_REQUEST_SUSCCESS = "UPDATE_TODO_REQUEST_SUSCCESS"
export const UPDATE_TODO_REQUEST_FAIL = "UPDATE_TODO_REQUEST_FAIL"


export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST"
export const DELETE_TODO_REQUEST_SUCCESS = "DELETE_TODO_REQUEST_SUCCESS"
export const DELETE_TODO_REQUEST_FAIL = "DELETE_TODO_REQUEST_FAIL"


export const DELETE_SINGLE_TODO_REQUEST = "DELETE_SINGLE_TODO_REQUEST"
export const DELETE_SINGLE_TODO_REQUEST_SUCCESS = "DELETE_SINGLE_TODO_REQUEST_SUCCESS"
export const DELETE_SINGLE_TODO_REQUEST_FAIL = "DELETE_SINGLE_TODO_REQUEST_FAIL"


export const UPDATE_STATUS_REQUEST = "UPDATE_STATUS_REQUEST"
export const UPDATE_STATUS_REQUEST_SUCCESS = "UPDATE_STATUS_REQUEST_SUCCESS"
export const UPDATE_STATUS_REQUEST_FAII = "UPDATE_STATUS_REQUEST_FAII"


