export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST"
export const USER_SIGNUP_REQUEST_SUCCESS = "USER_SIGNUP_REQUEST_SUCCESS"
export const USER_SIGNUP_REQUEST_FAIL = "USER_SIGNUP_REQUEST_FAIL"


export const USER_LOGIN_REQHEST = "USER_LOGIN_REQHEST"
export const USER_LOGIN_REQHEST_SUCCESS = "USER_LOGIN_REQHEST_SUCCESS"
export const USER_LOGIN_REQHEST_FAIL = "USER_LOGIN_REQHEST_FAIL"

export const USER_LOGOUT = "USER_LOGOUT"